name: wine-platform-runtime
version: v1.0
summary: wine platform runtime snap it provides WINE liberies for WINE
description: |
 This snap provides a WINE runtime liberies via content sharing to be used by other snaps that are using WINE.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386
base: core18

slots:
  wine-runtime:
    interface: content
    source:
      read:
      - $SNAP/bin
      - $SNAP/etc
      - $SNAP/lib
      - $SNAP/usr

parts:
  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  ppa:
    plugin: nil
    override-build: |
      snapcraftctl build
      apt-add-repository ppa:oibaf/graphics-drivers -y
      apt update
    build-packages:
      - software-properties-common
    after:
      - enable-i386

  wine-runtime:
    plugin: nil
    stage-packages:
      - libasound2
      - libavcodec57
      - libgphoto2-6
      - libgstreamer-plugins-base1.0-0
      - locales-all
      - liblcms2-2
      - libldap-2.4-2
      - libmpg123-0
      - libncurses5
      - libopenal1
      - libpcap0.8
      - libpulse0
      - libudev1
      - libxext6
      - libxml2
      - zlib1g
      - libcapi20-3
      - libcups2
      - libcanberra-gtk-module
      - libdbus-1-3
      - libfontconfig1
      - libfreetype6
      - libglu1-mesa
      - libgnutls30
      - libgsm1
      - libgssapi-krb5-2
      - libjpeg8
      - libodbc1
      - libosmesa6
      - libpng16-16
      - libsane
      - libsdl2-2.0-0
      - libtiff5
      - libv4l-0
      - libvulkan1
      - libxcomposite1
      - libxcursor1
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxxf86vm1
      - util-linux
      - winbind
      - samba-libs
      - mesa-vulkan-drivers
      - p7zip-full:i386
      - on amd64:
        - libasound2:i386
        - libavcodec57:i386
        - libgphoto2-6:i386
        - libgstreamer-plugins-base1.0-0:i386
        - locales-all:i386
        - liblcms2-2:i386
        - libldap-2.4-2:i386
        - libmpg123-0:i386
        - libncurses5:i386
        - libopenal1:i386
        - libpcap0.8:i386
        - libpulse0:i386
        - libudev1:i386
        - libxext6:i386
        - libxml2:i386
        - zlib1g:i386
        - libcapi20-3:i386
        - libcups2:i386
        - libcanberra-gtk-module:i386
        - libdbus-1-3:i386
        - libfontconfig1:i386
        - libfreetype6:i386
        - libglu1-mesa:i386
        - libgnutls30:i386
        - libgsm1:i386
        - libgssapi-krb5-2:i386
        - libjpeg8:i386
        - libodbc1:i386
        - libosmesa6:i386
        - libpng16-16:i386
        - libsane:i386
        - libsdl2-2.0-0:i386
        - libtiff5:i386
        - libv4l-0:i386
        - libvulkan1:i386
        - libxcomposite1:i386
        - libxcursor1:i386
        - libxfixes3:i386
        - libxi6:i386
        - libxinerama1:i386
        - libxrandr2:i386
        - libxrender1:i386
        - libxslt1.1:i386
        - libxxf86vm1:i386
        - winbind:i386
        - samba-libs:i386
        - mesa-vulkan-drivers:i386
        - p7zip-full:i386
    override-build: |
      snapcraftctl build
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init.d
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/logrotate.d
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/applications
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc-base
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pkgconfig
      # Remove stock glibc i386 files on amd64
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
       rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/audit
       rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/i386-linux-gnu/gconv
       for libs in ld-2.27.so libBrokenLocale-2.27.so libSegFault.so libanl-2.27.so libc-2.27.so libcidn-2.27.so libcrypt-2.27.so libdl-2.27.so libm-2.27.so libmemusage.so libnsl-2.27.so libnss_compat-2.27.so libnss_dns-2.27.so libnss_files-2.27.so libnss_hesiod-2.27.so libnss_nis-2.27.so libnss_nisplus-2.27.so libpcprofile.so libpthread-2.27.so libresolv-2.27.so librt-2.27.so libthread_db-1.0.so libutil-2.27.so; do
       rm $SNAPCRAFT_PART_INSTALL/lib/i386-linux-gnu/$libs
       done
      fi
    after:
      - ppa

  wine-platform-runtime:
    plugin: dump
    source: snap/local/scripts
    organize:
      'winetricks': bin/
      'zenity': bin/
      'wprfile': bin/
    stage-packages:
      - cabextract         # winetricks
      - libgdk-pixbuf2.0-0 # yad
      - libgtk-3-0         # yad
      - libnotify4         # yad
      - libnotify-bin      # sommelier
      - perl-base          # winetricks
      - shared-mime-info
      - unzip              # winetricks
      - wget               # winetricks
      - x11-xserver-utils  # sommelier
      - yad                # winetricks
    override-build: |
      snapcraftctl build
      wget --quiet "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -O $SNAPCRAFT_PART_INSTALL/winetricks
      chmod +x $SNAPCRAFT_PART_INSTALL/winetricks
      touch $SNAPCRAFT_PART_INSTALL/wprfile
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init.d
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/logrotate.d
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/fc-*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/gtk-*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/dconf/dconf-service
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/glib-networking/glib-pacrunner
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/GConf
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/aclocal
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apport
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bash-completion
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc-base
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/Adwaita
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/Humanity*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/LoginIcons
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/ubuntu-mono*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/info
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/kde4
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/menu
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/perl5
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pkgconfig
    after:
      - wine-runtime

  libc-lol-patched:
    plugin: nil
    after: [wine-platform-runtime]
    override-build: |
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        wget https://gist.github.com/mmtrt/578f4c0694fcfc968b2d9dcc90da4c0e/raw/d509248e78c734f648972d8119c7217c47d7ce27/libc6_2.27-3ubuntu1_i386.deb
        dpkg -x libc6_2.27-3ubuntu1_i386.deb $SNAPCRAFT_PART_INSTALL
      fi

  fixup-vulkan-icd-paths:
    plugin: nil
    after: [libc-lol-patched]
    override-build: |
      sed -i -E 's,(^.+"library_path": ")/.*/,\1,' $SNAPCRAFT_STAGE/usr/share/vulkan/icd.d/*.json
      wget -nvc https://gist.github.com/mmtrt/8d1a2b9eb33429feb0197ec46b0acdf4/raw/a8082e47f3a9c2a4f5acd8cf81da6ec62c00d5fc/nvidia_icd.json -P $SNAPCRAFT_PART_INSTALL/usr/share/vulkan/icd.d